server:
  name: My-app
  port: :3000
database:
  host: localhost
  port: :3306
  user: root
  password: 1210
  name: test
jwtkey: secret
App:
  host: localhost
  port: :5173
Redis:
  host: localhost
  port: :6379
  password: 
  db: 0
